export default {
  STRING: "s",
  NUMBER: "n",
  UTS_PREFIX: "uts",
  BOOL: "b",
  NULL: "null",
  COLLECTION_NAME: "collection",
  PATH_TO_VALUE: "value",
  DELETED: "deleted",
  STORAGE_MAP: "m",
  STORAGE_VECTOR: "v",
  // QUERIES
  QUERY_SET: "q",
  INSERT_QUERY: "insert",
  FIND_QUERY: "find",
  GET_QUERY: "get",
  UPDATE_QUERY: "update",
  DELETE_QUERY: "delete",
  SORT_QUERY: "sort",
  OFFSET_QUERY: "offset",
  LIMIT_QUERY: "limit",
  // FIND OPERATORS
  EQ_OPERATOR: "eq",
  NEQ_OPERATOR: "neq",
  GT_OPERATOR: "gt",
  GTE_OPERATOR: "gte",
  LT_OPERATOR: "lt",
  LTE_OPERATOR: "lte",
  AND_OPERATOR: "and",
  OR_OPERATOR: "or",
  NOT_OPERATOR: "not",
  // UPDATE OPERATORS
  SET_OPERATOR: "set",
  INC_OPERATOR: "inc",
  // SORT OPERATORS
  ASC_OPERATOR: "asc",
  DESC_OPERATOR: "desc",
  // RESPONSE
  RESPONSE_OBJECTS: "objects",
  RESPONSE_IDS: "ids",
  RESPONSE: "data",
  RESPONSE_PRIMITIVE: "result",
  OK_RESPONSE: "ok",
  ERROR_RESPONSE: "error",
  QUERY_RESPONSE: "response",
  INSERT_META: "insert_meta",
  GET_META: "get_meta",
  UPDATE_META: "update_meta",
  FIND_META: "find_meta",
  DELETE_META: "delete_meta",
  // OTHER
  ROOT: "root",
  INTERNAL_COLLECTION_NAME: "_internal",
};
